name: build
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hipagesgroup/actions/install-dependencies@master
        with:
          language: Python
          version: 3.9
          cache: pip
      - run: python main.py
